apiVersion: v1
kind: ServiceAccount
metadata:
  name: mlflow
  annotations:
    eks.amazonaws.com/role-arn: REPLACE_WITH_MLFLOW_ROLE_ARN
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: pipeline
  annotations:
    eks.amazonaws.com/role-arn: REPLACE_WITH_PIPELINE_ROLE_ARN
